# Generated by Django 6.0.3 on 2026-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='request_type',
            field=models.CharField(choices=[('mentorship', 'Mentorship'), ('referral', 'Referral')], default='mentorship', max_length=20),
            preserve_default=False,
        ),
    ]
