# Generated by Django 6.0.3 on 2026-03-14 07:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connectionrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectionrequest',
            unique_together={('student', 'alumni', 'request_type')},
        ),
    ]
