# Generated by Django 6.0.3 on 2026-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='role',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
