# Generated by Django 6.0.3 on 2026-03-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
