# Generated by Django 6.0.3 on 2026-03-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumniprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
